pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/saieswar90/jenkins-react.git', branch: "${env.BRANCH_NAME}"
            }
        }

        stage('Build and Test') {
            stages {
                stage('Install') {
                    steps { bat 'npm install' }
                }
                stage('Test') {
                    steps { bat 'npx vitest run' }
                }
                stage('Build') {
                    steps { bat 'npm run build' }
                }
            }
        }

        stage('Deployment') {
            when {
                expression { currentBuild.currentResult == 'SUCCESS' }
            }
            stages {
                stage('Staging') {
                    when { branch 'development' }
                    steps { echo "Deploying to STAGING" }
                }
                stage('Production') {
                    when { branch 'main' }
                    steps { echo "Deploying to PRODUCTION" }
                }
            }
        }
    }
}
